services:
  n8n:
    build: .
    image: n8n-pterodactyl:local
    container_name: n8n
    ports:
      - "5678:5678" 
    volumes:
      - n8n_data:/home/container
    environment:
      # Simulasikan variabel yang biasanya diinjeksi Pterodactyl
      SERVER_PORT: "5678"
      STARTUP: "n8n start"
      GENERIC_TIMEZONE: "Asia/Jakarta"
      N8N_SECURE_COOKIE: "false"
      N8N_ENCRYPTION_KEY: "ganti-dengan-string-acak-yang-aman"
      # WEBHOOK_URL: "https://n8n.domainkamu.com/"
    restart: unless-stopped

volumes:
  n8n_data:
